### PR TITLE
Shadow DOM [Experimental]

### PR DESCRIPTION
**Pull request by karak**
Experimental another implementation of `template` to work with Shadow DOM.
I created this for my private demonstration.

Demo is also uploaded to this Plunker: <http://plnkr.co/edit/4YGrNBNDEmIJXT1SdMdR?p=preview>.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
wow thanks..I will have a look at it asap

**Comment by karak** [comment]
anytime you want.

and I'll look into coverage. jsdom has no shadow DOM.

**Comment by GianlucaGuarini** [comment]
I have checked your patch and I had some thoughts about it. This repo hosts only the new riot dom bindings so it was not meant to be used to style a component or creating custom components or whatsoever. I think this patch will make more sense in [riot itself](https://github.com/riot/riot/blob/next/lib/core/component.js) where we will be using the dom binding to handle the DOM updates. I appreciate your effort but at moment I need support for handling the `each={}` directive or `each={} + if={}` in this repo. The Shadow DOM support will come once all the bindings will be ready.

**Comment by karak** [comment]
@GianlucaGuarini Thank you for your review. All right! I greatly expect the future.

**Comment by karak** [comment]
BTW, I'll leave some notes about shadow DOM for the future, for broader support of Shadow DOM might press that border.

1. Abuse of `cloneNode(deep)`

`cloneNode` of shadowRoot nor that of element with shadowRoot doesn't and shouldn't work as expected here. In fact, this is one of the major motivation of my work.

2. Some features of scoped CSS requires more live manipulation, if any, for example:

- CSS variables. Actually, is it an expression of dom-bindings?
- CSS boundary(a.k.a. "all: initial") could increase works of instance/element side.

**Comment by GianlucaGuarini** [comment]
thanks for the idea but I am going to close this PR since I will probably implement this feature directly in riot and not in its template engine. In case you would like to help you try working on one of the [repo issues](https://github.com/riot/dom-bindings/issues)

**Pull request closed without merging**
